include:
  - ../traefik/networks.compose.yaml

services:
  beszel:
    image: ghcr.io/henrygd/beszel/beszel:0.18
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: https://beszel.${TAILNET_DOMAIN:?TAILNET_DOMAIN variable not set}
    volumes:
      - beszel_data:/beszel_data
      - beszel_socket:/beszel_socket
    healthcheck:
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]
      interval: 120s
      start_period: 10s
      timeout: 5s
    networks:
      - traefik-beszel
    labels:
      traefik.enable: true
      traefik.http.routers.beszel.rule: Host(`beszel.${TAILNET_DOMAIN:?TAILNET_DOMAIN variable not set}`)
      traefik.http.services.beszel.loadbalancer.server.port: 8090
      traefik.http.routers.beszel.entrypoints: websecure

  beszel-agent:
    image: ghcr.io/henrygd/beszel/beszel-agent-intel:0.18
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    cap_add:
      - CAP_PERFMON
      - SYS_RAWIO
    devices:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/sda:/dev/sda
      - /dev/sda:/dev/sdb
      - /dev/sda:/dev/sdc
      - /dev/sda:/dev/sdd
      - /dev/sda:/dev/sde
      - /dev/sda:/dev/sdf
      - /dev/sda:/dev/sdg
    volumes:
      - beszel_agent_data:/var/lib/beszel-agent
      - beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/SigmaPool:/extra_filesystems/SigmaPool:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      TOKEN: ${BESZEL_TOKEN:?BESZEL_TOKEN variable not set}
      KEY: ${BESZEL_KEY:?BESZEL_KEY variable not set}
    healthcheck:
      test: ["CMD", "/agent", "health"]
      interval: 120s

volumes:
  beszel_data:
    name: beszel_data
    driver: local
  beszel_socket:
    name: beszel_socket
    driver: local
  beszel_agent_data:
    name: beszel_agent_data
    driver: local
