services:
  hbbs:
    container_name: rustdesk-hbbs
    image: ghcr.io/rustdesk/rustdesk-server:1
    command: hbbs
    depends_on:
      - hbbr
    restart: unless-stopped
    volumes:
      - rustdesk_data:/root
    network_mode: host

  hbbr:
    container_name: rustdesk-hbbr
    image: ghcr.io/rustdesk/rustdesk-server:1
    command: hbbr
    restart: unless-stopped
    volumes:
      - rustdesk_data:/root
    network_mode: host

volumes:
  rustdesk_data:
    name: rustdesk_data
    driver: local
