##
## Server Configuration
##
theme: 'dark'   # light, dark, grey, auto
server:
  address: 'tcp://:9091/'
  asset_path: '/app_data/assets/'


##
## Log Configuration
##
log:
  level: 'info'
  format: 'json'
  file_path: '/logs/authelia.log'
  keep_stdout: false


##
## TOTP Configuration
##
totp:
  disable: false
  algorithm: 'SHA1'
  digits: 6
  period: 30
  skew: 1
  secret_size: 32


##
## WebAuthn Configuration
##
webauthn:
  disable: false
  enable_passkey_login: true
  attestation_conveyance_preference: 'indirect'
  timeout: '60 seconds'


##
## Identity Validation Configuration
##
identity_validation:
  reset_password:
    jwt_lifespan: '15 minutes'
    jwt_algorithm: 'HS256'


##
## NTP Configuration
##
ntp:
  disable_startup_check: true
  disable_failure: true


##
## Authentication Backend Provider Configuration
##
authentication_backend:
  ldap:
    implementation: 'lldap'
    address: 'ldap://lldap:3890'


##
## Password Policy Configuration.
##
password_policy:
  zxcvbn:
    enabled: true
    min_score: 2


##
## Privacy Policy Configuration
##
privacy_policy:
  enabled: false


##
## Session Provider Configuration
##
# session:
#   cookies:
#     - name: 'authelia_session'
#       same_site: 'lax'
#       inactivity: '20 minutes'
#       expiration: '5 hours'
#       remember_me_duration: '2 months'


##
## Regulation Configuration
##
regulation:
  modes:
    - 'user'
  max_retries: 5
  find_time: '5 minutes'
  ban_time: '5 minutes'


##
## Storage Provider Configuration
##
storage:
  local:
    path: '/app_data/db.sqlite3'


##
## Notification Provider
##
notifier:
  filesystem:
    filename: '/app_data/notification.txt'


##
## Identity Providers
##
identity_providers:

  ##
  ## OpenID Connect
  ##
  oidc:
    enable_client_debug_messages: false
    minimum_parameter_entropy: 8
    enforce_pkce: 'public_clients_only'
    enable_pkce_plain_challenge: false
    enable_jwt_access_token_stateless_introspection: false
    discovery_signed_response_alg: 'none'
    require_pushed_authorization_requests: false
    lifespans:
      access_token: '1h'
      authorize_code: '1m'
      id_token: '1h'
      refresh_token: '90m'
    cors:
      endpoints:
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
        - 'pushed-authorization-request'
        - 'userinfo'